apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile2
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard
  location: Central India
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: "azurefile2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi